class StudentRegistrationModel {
  String? registrationNumber;
  String? lurnCertificate;
  String? candidateName;
  String? fatherName;
  String? annualIncomeRs;
  String? occupation;
  String? motherName;
  String? motherAnnualIncomeRs;
  String? motherOccupation;
  String? dateOfBirth;
  String? mobileNumber;
  String? aadharId;
  String? emailId;
  String? gender;
  String? category;
  String? course;
  String? bloodGroup;
  String? religion;
  String? caste;
  String? nationality;
  String? examinationName;
  String? institution;
  String? boardUniversity;
  String? passingYear;
  String? maximumMarks;
  String? marksObtained;
  String? marksPercentage;
  String? fatherMobileNo;
  String? motherMobileNumber;
  String? presentAddress;
  String? presentPincode;
  String? presentNearRailway;
  String? presentNearPolice;
  String? permanentAddress;
  String? permanentPincode;
  String? permanentNearRailway;
  String? permanentNearPolice;
  String? domicileCertificatePath;
  String? casteCertificatePath;
  String? addressProofPath;
  String? studentPhotoPath;
  String? studentSignaturePath;
  String? interMarksheetPath;

  Map<String, dynamic> toJson() => {
        'registrationnumber': registrationNumber,
        'lurncertificate': lurnCertificate,
        'candidatename': candidateName,
        'fathername': fatherName,
        'annualincomers': annualIncomeRs,
        'occupation': occupation,
        'mothername': motherName,
        'motherannualincomers': motherAnnualIncomeRs,
        'motheroccupation': motherOccupation,
        'dateofbirth': dateOfBirth,
        'mobilenumber': mobileNumber,
        'aadharid': aadharId,
        'emailid': emailId,
        'gender': gender,
        'category': category,
        'course': course,
        'bloodgroup': bloodGroup,
        'religion': religion,
        'caste': caste,
        'nationality': nationality,
        'examinationname': examinationName,
        'institution': institution,
        'boarduniversity': boardUniversity,
        'passingyear': passingYear,
        'maximummarks': maximumMarks,
        'marksobtained': marksObtained,
        'markspercentage': marksPercentage,
        'fathermobileno': fatherMobileNo,
        'mothermobilenumber': motherMobileNumber,
        'presentaddress': presentAddress,
        'presentpincode': presentPincode,
        'presentnearrailway': presentNearRailway,
        'presentnearpolice': presentNearPolice,
        'permanentaddress': permanentAddress,
        'permanentpincode': permanentPincode,
        'permanentnearrailway': permanentNearRailway,
        'permanentnearpolice': permanentNearPolice,
        'domicilecertificate': domicileCertificatePath,
        'castecertificate': casteCertificatePath,
        'addressproof': addressProofPath,
        'studentphoto': studentPhotoPath,
        'studentsignature': studentSignaturePath,
        'intermarksheet': interMarksheetPath,
      };
}
